# Generated by Django 5.2.11 on 2026-08-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_commentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted_due_to_violation',
            field=models.BooleanField(db_index=True, default=False, help_text='Оказва дали обектът е премахнат заради нарушение.'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_user_informed_about_violation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_violation_info',
            field=models.JSONField(blank=True, help_text='Детайли за последното нарушение (напр. причина, модератор, дата).', null=True),
        ),
    ]
