# Generated by Django 5.2.11 on 2026-08-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_commentappeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentappeal',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
