# Generated by Django 5.2.11 on 2026-02-15 19:49

import core.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('programmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': 'Максималната дължина е 255 символа!'}, max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('min_price', models.DecimalField(decimal_places=2, error_messages={'decimal_places': 'Максималната дължина след десетичната запетая е 2 цифри!', 'max_digits': 'Максималната дължина е 10 цифри!'}, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, error_messages={'decimal_places': 'Максималната дължина след десетичната запетая е 2 цифри!', 'max_digits': 'Максималната дължина е 10 цифри!'}, max_digits=10)),
                ('programmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='programmers.programmer')),
                ('technologies', models.ManyToManyField(related_name='services', to='categories.technology')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='categories.type')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'programmer'), name='unique_service_for_programmer', violation_error_message='Този програмист вече е предложил същата услуга!')],
            },
            bases=(core.mixins.CreatedAndUpdatedAtMixin, models.Model),
        ),
    ]
