# Generated by Django 5.2.11 on 2026-03-26 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_devradaruser_options_and_more'),
        ('services', '0002_alter_service_programmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='programmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.programmeruser'),
        ),
    ]
