# Generated by Django 5.2.11 on 2026-06-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_programmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
