# Generated by Django 5.2.11 on 2026-06-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_deleted_due_to_ban',
            field=models.BooleanField(default=False),
        ),
    ]
