# Generated by Django 5.2.11 on 2026-06-17 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_is_deleted_due_to_ban'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('spam', 'Спам'), ('harassment', 'Тормоз'), ('hate_speech', 'Реч на омразата'), ('violence', 'Насилие или заплахи'), ('sexual_content', 'Сексуално съдържание'), ('scam', 'Измама'), ('misinformation', 'Дезинформация'), ('copyright', 'Нарушение на авторски права'), ('other', 'Друго')], default='other')),
                ('description', models.TextField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
