# Generated by Django 5.2.11 on 2026-08-13 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_is_deleted_due_to_violation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereport',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='services.service'),
        ),
    ]
