# Generated by Django 5.2.11 on 2026-09-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_serviceappeal_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
