# Generated by Django 5.2.11 on 2026-09-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_programmeruser_bio_programmeruser_site'),
        ('categories', '0003_technology_created_at_technology_updated_at_and_more'),
        ('services', '0012_service_created_at_service_updated_at'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='service',
            name='unique_service_for_programmer',
            constraint=models.UniqueConstraint(fields=('name', 'programmer'), name='unique_service_for_programmer', violation_error_message='Този програмист/фирма вече е предложил/а същата услуга!'),
        ),
    ]
