# Generated by Django 5.2.11 on 2026-06-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messagereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
