# Generated by Django 5.2.11 on 2026-08-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messagereport_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereport',
            name='context_messages',
            field=models.ManyToManyField(related_name='message_reports', to='chat.message'),
        ),
    ]
