# Generated by Django 5.2.11 on 2026-08-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_message_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted_due_to_ban',
            field=models.BooleanField(default=False),
        ),
    ]
