# Generated by Django 5.2.11 on 2026-08-13 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereport',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat.message'),
        ),
    ]
