# Generated by Django 5.2.11 on 2026-09-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_messageappeal_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
