# Generated by Django 5.2.11 on 2026-03-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devradaruser',
            name='phone',
        ),
        migrations.AddField(
            model_name='devradaruser',
            name='image',
            field=models.ImageField(default=9, upload_to='programmers/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devradaruser',
            name='phone_number',
            field=models.CharField(default=9, error_messages={'max_length': 'Максималната дължина е 15 символа!', 'unique': 'Програмист с този тел. номер вече съществува!'}, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devradaruser',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='devradaruser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Програмист с този имейл вече съществува!'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='devradaruser',
            name='first_name',
            field=models.CharField(error_messages={'max_length': 'Максималната дължина е 100 символа!'}, max_length=150, verbose_name='first name'),
        ),
    ]
