# Generated by Django 5.2.11 on 2026-03-26 16:45

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_devradaruser_phone_devradaruser_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devradaruser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='devradaruser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='devradaruser',
            name='slug',
        ),
        migrations.CreateModel(
            name='ProgrammerUser',
            fields=[
                ('devradaruser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(upload_to='programmers/')),
                ('phone_number', models.CharField(error_messages={'max_length': 'Максималната дължина е 15 символа!', 'unique': 'Програмист с този тел. номер вече съществува!'}, max_length=15, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('accounts.devradaruser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
