# Generated by Django 5.2.11 on 2026-03-26 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_devradaruser_image_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devradaruser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='programmeruser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='devradaruser',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='programmeruser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='devradaruser',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
