# Generated by Django 5.2.11 on 2026-03-27 19:35

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_devradaruser_options_and_more'),
        ('services', '0003_alter_service_programmer'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='devradaruser',
            managers=[
                ('objects', accounts.models.DevRadarUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='programmeruser',
            managers=[
                ('objects', accounts.models.DevRadarUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='devradaruser',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='users', to='services.service'),
        ),
    ]
