# Generated by Django 5.2.11 on 2026-04-02 14:12
from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.contrib.auth.management import create_permissions


def create_group_and_user(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

    Group = apps.get_model('auth', 'Group')
    DevRadarUser = apps.get_model('accounts', 'DevRadarUser')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    editors_group, _ = Group.objects.get_or_create(name='Editors')

    codenames = ['add_type', 'change_type', 'delete_type', 'add_technology']
    perms = Permission.objects.filter(codename__in=codenames)
    editors_group.permissions.add(*perms)

    if not DevRadarUser.objects.filter(username='editor').exists():
        user_ct = ContentType.objects.get_for_model(DevRadarUser)

        user = DevRadarUser.objects.create(
            username='editor',
            password=make_password('abcabcabc1'),
            email='editor@example.com',
            first_name='Editor',
            last_name='Editor',
            polymorphic_ctype=user_ct,
        )
        user.groups.add(editors_group)

    programmers_group, _ = Group.objects.get_or_create(name='Programmers')
    prog_perm = Permission.objects.filter(codename='add_service').first()
    if prog_perm:
        programmers_group.permissions.add(prog_perm)


def reverse_func(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    DevRadarUser = apps.get_model('accounts', 'DevRadarUser')
    DevRadarUser.objects.filter(username='editor').delete()
    Group.objects.filter(name__in=['Editors', 'Programmers']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_alter_devradaruser_managers_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_group_and_user, reverse_func),
    ]
