# Generated by Django 5.2.11 on 2026-04-02 14:12

from django.db import migrations

from django.contrib.auth.hashers import make_password

def create_group_and_user(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    User = apps.get_model('accounts', 'DevRadarUser')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')

    editors_group, _ = Group.objects.get_or_create(name='Editors')

    permission = Permission.objects.get(codename='add_type')
    editors_group.permissions.add(permission)
    permission = Permission.objects.get(codename='change_type')
    editors_group.permissions.add(permission)
    permission = Permission.objects.get(codename='delete_type')
    editors_group.permissions.add(permission)
    permission = Permission.objects.get(codename='add_technology')
    editors_group.permissions.add(permission)

    if not User.objects.filter(username='editor').exists():
        user = User.objects.create(
            username='editor',
            password=make_password('abcabcabc1'),
            email='editor@example.com',
            first_name='Editor',
            last_name='Editor',
            polymorphic_ctype=ContentType.objects.get_for_model(User),
        )

        user.groups.add(editors_group)

    programmers_group, _ = Group.objects.get_or_create(name='Programmers')

    permission = Permission.objects.get(codename='add_service')
    programmers_group.permissions.add(permission)

def reverse_func(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    User = apps.get_model('accounts', 'DevRadarUser')

    User.objects.filter(username='editor').delete()
    Group.objects.filter(name='Editors').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_devradaruser_managers_and_more'),
        ('contenttypes', '0002_remove_content_type_name')
    ]

    operations = [
        migrations.RunPython(create_group_and_user, reverse_func),
    ]
