# Generated by Django 5.2.11 on 2026-05-25 15:39
import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_ban_end_date_alter_ban_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ban',
            name='end_date',
        ),
        migrations.AddField(
            model_name='ban',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ban',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
