# Generated by Django 5.2.11 on 2026-05-25 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_ban_end_date_ban_duration_ban_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=1)),
        ),
    ]
