# Generated by Django 5.2.11 on 2026-05-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_ban_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='duration',
            field=models.DurationField(blank=True),
        ),
    ]
