# Generated by Django 5.2.11 on 2026-05-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_ban_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='ban_type',
            field=models.CharField(choices=[('CHAT_BAN', 'Chat ban'), ('COMMENTS_BAN', 'Comments ban'), ('OFFER_SERVICE_BAN', 'Ofer service ban'), ('BAN', 'Ban')], default='BAN', max_length=20),
        ),
    ]
