# Generated by Django 5.2.11 on 2026-06-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_ban_ban_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ban',
        ),
    ]
