# Generated by Django 5.2.11 on 2026-08-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_delete_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devradaruser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Потребител с този имейл вече съществува!'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
