# Generated by Django 5.2.11 on 2026-08-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_devradaruser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='devradaruser',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programmeruser',
            name='phone_number',
            field=models.CharField(error_messages={'max_length': 'Максималната дължина е 15 символа!'}, max_length=15),
        ),
    ]
