# Generated by Django 5.2.11 on 2026-09-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_devradaruser_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmeruser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programmers/'),
        ),
        migrations.AlterField(
            model_name='programmeruser',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'max_length': 'Максималната дължина е 15 символа!'}, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='programmeruser',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
