# Generated by Django 5.2.11 on 2026-09-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_programmeruser_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devradaruser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
    ]
