# Generated by Django 5.2.11 on 2026-09-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_devradaruser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeruser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programmeruser',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
