# Generated by Django 5.2.11 on 2026-09-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_programmeruser_bio_programmeruser_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='devradaruser',
            name='pixel_registration_tracked',
            field=models.BooleanField(default=False, help_text='Определя дали CompleteRegistration събитието за Meta Pixel е било задействано.'),
        ),
    ]
