# Generated by Django 5.2.11 on 2026-02-15 19:49

import core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(error_messages={'max_length': 'Максималната дължина е 100 символа!', 'unique': 'Технологията вече съществува!'}, max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='categories/technologies/')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.mixins.CreatedAndUpdatedAtMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(error_messages={'max_length': 'Максималната дължина е 100 символа!', 'unique': 'Типът услуга вече съществува!'}, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='categories/types/')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.mixins.CreatedAndUpdatedAtMixin, models.Model),
        ),
    ]
