# Generated by Django 5.2.11 on 2026-09-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_technology_created_at_technology_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['name']},
        ),
    ]
