# Generated by Django 5.2.11 on 2026-09-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_technology_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['id']},
        ),
    ]
