# Generated by Django 5.2.11 on 2026-06-02 16:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(blank=True)),
                ('permanent', models.BooleanField(default=False)),
                ('ban_type', models.CharField(choices=[('CHAT_BAN', 'Chat ban'), ('COMMENTS_BAN', 'Comments ban'), ('OFFER_SERVICE_BAN', 'Offer service ban'), ('FULL_BAN', 'Full ban')], default='FULL_BAN', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
