# Generated by Django 5.2.11 on 2026-06-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_reportedcomment_reportedmessage_reportedservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportedComment',
        ),
        migrations.DeleteModel(
            name='ReportedMessage',
        ),
        migrations.DeleteModel(
            name='ReportedService',
        ),
    ]
