# Generated by Django 5.2.11 on 2026-08-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_delete_reportedcomment_delete_reportedmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
