# Generated by Django 5.2.11 on 2026-02-15 19:49

import core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(error_messages={'max_length': 'Максималната дължина е 100 символа!'}, max_length=100)),
                ('last_name', models.CharField(error_messages={'max_length': 'Максималната дължина е 100 символа!'}, max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'Програмист с този имейл вече съществува!'}, max_length=254, unique=True)),
                ('phone_number', models.CharField(error_messages={'max_length': 'Максималната дължина е 15 символа!', 'unique': 'Програмист с този тел. номер вече съществува!'}, max_length=15, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            bases=(core.mixins.CreatedAndUpdatedAtMixin, models.Model),
        ),
    ]
