# Generated by Django 5.2.11 on 2026-02-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='image',
            field=models.ImageField(default=1, upload_to='programmers/'),
            preserve_default=False,
        ),
    ]
