# Generated by Django 5.2.11 on 2026-09-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmers', '0003_programmer_created_at_programmer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmer',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Програмист/фирма с този имейл вече съществува!'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='phone_number',
            field=models.CharField(error_messages={'max_length': 'Максималната дължина е 15 символа!', 'unique': 'Програмист/фирма с този тел. номер вече съществува!'}, max_length=15, unique=True),
        ),
    ]
